#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

psp_files = [
    "godot_psp.cpp",
    "os_psp.cpp",
    "psp_log.cpp",
    "psp_logger.cpp",
    "psp_posix_stubs.cpp",
    "psp_ctrl_map.cpp",
    "psp_selftest.cpp",
]

prog = env.add_program("#bin/godot", psp_files)
